create table public.activity_logs (
  id uuid not null default extensions.uuid_generate_v4 (),
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  action text not null,
  description text null,
  context text null,
  user_id uuid null,
  user_email text null,
  entity_type text null,
  entity_id text null,
  metadata jsonb null,
  constraint activity_logs_pkey primary key (id),
  constraint activity_logs_context_check check (
    (
      (context is null)
      or (
        context = any (
          array['public'::text, 'admin'::text, 'system'::text]
        )
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists activity_logs_user_id_idx on public.activity_logs using btree (user_id) TABLESPACE pg_default;

create index IF not exists activity_logs_context_idx on public.activity_logs using btree (context) TABLESPACE pg_default;

create index IF not exists activity_logs_created_at_idx on public.activity_logs using btree (created_at) TABLESPACE pg_default;


create table public."adminUsers" (
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  email character varying null,
  role text null default 'user'::text,
  constraint adminUsers_pkey primary key (user_id),
  constraint adminUsers_user_id_key unique (user_id),
  constraint adminusers_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create table public.blog_categories (
  id uuid not null default extensions.uuid_generate_v4 (),
  name text not null,
  slug text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint blog_categories_pkey primary key (id),
  constraint blog_categories_name_key unique (name),
  constraint blog_categories_slug_key unique (slug)
) TABLESPACE pg_default;

create table public.contact_messages (
  id bigint generated by default as identity not null,
  name text not null,
  email text not null,
  subject text null,
  message text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  phone text null,
  status text not null default 'open'::text,
  constraint contact_messages_pkey primary key (id),
  constraint contact_messages_status_check check (
    (
      status = any (
        array['open'::text, 'in_progress'::text, 'done'::text]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists contact_messages_created_at_idx on public.contact_messages using btree (created_at desc) TABLESPACE pg_default;

create table public.homepage_benefits (
  id uuid not null default extensions.uuid_generate_v4 (),
  title text not null,
  description text not null,
  display_order integer not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint homepage_benefits_pkey primary key (id),
  constraint homepage_benefits_display_order_check check (
    (
      (display_order >= 1)
      and (display_order <= 3)
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists homepage_benefits_display_order_idx on public.homepage_benefits using btree (display_order) TABLESPACE pg_default;

create trigger homepage_benefits_set_updated_at BEFORE
update on homepage_benefits for EACH row
execute FUNCTION homepage_benefits_set_updated_at ();

create table public.homepage_images (
  id uuid not null default gen_random_uuid (),
  image_type text not null,
  file_path text not null,
  public_url text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint homepage_images_pkey primary key (id),
  constraint homepage_images_image_type_key unique (image_type),
  constraint homepage_images_image_type_check check (
    (
      image_type = any (array['background'::text, 'overlay'::text])
    )
  )
) TABLESPACE pg_default;

create table public.homepage_photographer_intro (
  id uuid not null default extensions.uuid_generate_v4 (),
  singleton_key text not null default 'homepage'::text,
  heading text not null,
  subheading text null,
  body text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint homepage_photographer_intro_pkey primary key (id),
  constraint homepage_photographer_intro_singleton unique (singleton_key)
) TABLESPACE pg_default;

create trigger homepage_photographer_intro_set_updated_at BEFORE
update on homepage_photographer_intro for EACH row
execute FUNCTION homepage_photographer_intro_set_updated_at ();

create table public.homepage_reviews (
  id uuid not null default extensions.uuid_generate_v4 (),
  author text not null,
  role text null,
  quote text not null,
  rating smallint not null default 5,
  display_order integer not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint homepage_reviews_pkey primary key (id),
  constraint homepage_reviews_rating_check check (
    (
      (rating >= 1)
      and (rating <= 5)
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists homepage_reviews_display_order_idx on public.homepage_reviews using btree (display_order) TABLESPACE pg_default;

create trigger homepage_reviews_set_updated_at BEFORE
update on homepage_reviews for EACH row
execute FUNCTION homepage_reviews_set_updated_at ();

create table public.homepage_usps (
  id uuid not null default extensions.uuid_generate_v4 (),
  title text not null,
  description text not null,
  display_order integer not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint homepage_usps_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists homepage_usps_display_order_idx on public.homepage_usps using btree (display_order) TABLESPACE pg_default;

create trigger homepage_usps_set_updated_at BEFORE
update on homepage_usps for EACH row
execute FUNCTION homepage_usps_set_updated_at ();

create table public.page_metadata (
  slug text not null,
  title text null,
  description text null,
  open_graph_title text null,
  open_graph_description text null,
  open_graph_image_url text null,
  canonical_url text null,
  keywords text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint page_metadata_pkey primary key (slug),
  constraint page_metadata_slug_check check ((char_length(slug) > 0))
) TABLESPACE pg_default;

create trigger set_page_metadata_updated_at BEFORE
update on page_metadata for EACH row
execute FUNCTION trigger_set_timestamp ();

create table public.portfolio_project_images (
  id uuid not null default extensions.uuid_generate_v4 (),
  project_id uuid not null,
  caption text null,
  file_path text not null,
  public_url text not null,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  alt_text text null,
  meta_title text null,
  meta_description text null,
  meta_keywords text null,
  constraint portfolio_project_images_pkey primary key (id),
  constraint portfolio_project_images_project_id_fkey foreign KEY (project_id) references portfolio_projects (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists portfolio_project_images_project_idx on public.portfolio_project_images using btree (project_id, display_order, created_at) TABLESPACE pg_default;

create table public.portfolio_projects (
  id uuid not null default extensions.uuid_generate_v4 (),
  title text not null,
  subtitle text null,
  excerpt text null,
  slug text null,
  cover_public_url text null,
  display_order integer not null default 0,
  is_featured boolean not null default false,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint portfolio_projects_pkey primary key (id),
  constraint portfolio_projects_slug_key unique (slug)
) TABLESPACE pg_default;

create index IF not exists portfolio_projects_display_order_idx on public.portfolio_projects using btree (display_order, created_at) TABLESPACE pg_default;

create trigger portfolio_projects_set_updated_at BEFORE
update on portfolio_projects for EACH row
execute FUNCTION portfolio_projects_set_updated_at ();

create table public.portfolio_settings (
  id uuid not null default extensions.uuid_generate_v4 (),
  hero_headline text null,
  hero_subheadline text null,
  hero_description text null,
  hero_cta_label text null,
  hero_cta_url text null,
  background_file_path text null,
  background_public_url text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint portfolio_settings_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists portfolio_settings_singleton_idx on public.portfolio_settings using btree ((true)) TABLESPACE pg_default;

create trigger portfolio_settings_set_updated_at BEFORE
update on portfolio_settings for EACH row
execute FUNCTION portfolio_settings_set_updated_at ();

create table public.posts (
  id bigint generated always as identity not null,
  author_id uuid null,
  title text not null,
  slug text not null,
  excerpt text null,
  content text not null,
  cover_image text null,
  status text not null default 'draft'::text,
  published_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  spotlight boolean not null default false,
  category_id uuid null,
  constraint posts_pkey primary key (id),
  constraint posts_slug_key unique (slug),
  constraint posts_author_id_fkey foreign KEY (author_id) references auth.users (id) on delete set null,
  constraint posts_category_id_fkey foreign KEY (category_id) references blog_categories (id) on delete set null,
  constraint posts_status_check check (
    (
      status = any (
        array[
          'draft'::text,
          'published'::text,
          'archived'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists posts_spotlight_true_idx on public.posts using btree (spotlight) TABLESPACE pg_default
where
  (spotlight is true);

create trigger posts_set_updated_at BEFORE
update on posts for EACH row
execute FUNCTION set_updated_at ();

create table public.service_portfolio_projects (
  id uuid not null default extensions.uuid_generate_v4 (),
  service_slug text not null,
  project_id uuid not null,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint service_portfolio_projects_pkey primary key (id),
  constraint service_portfolio_projects_unique unique (service_slug, project_id),
  constraint service_portfolio_projects_project_id_fkey foreign KEY (project_id) references portfolio_projects (id) on delete CASCADE,
  constraint service_portfolio_projects_service_slug_fkey foreign KEY (service_slug) references services (slug) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists service_portfolio_projects_service_idx on public.service_portfolio_projects using btree (service_slug, display_order, created_at) TABLESPACE pg_default;

create trigger service_portfolio_projects_set_updated_at BEFORE
update on service_portfolio_projects for EACH row
execute FUNCTION service_portfolio_projects_set_updated_at ();

create table public.service_slide_images (
  id uuid not null default extensions.uuid_generate_v4 (),
  service_slug text not null,
  file_path text not null,
  public_url text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint service_slide_images_pkey primary key (id),
  constraint service_slide_images_service_slug_key unique (service_slug),
  constraint service_slide_images_service_slug_fkey foreign KEY (service_slug) references services (slug) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists service_slide_images_service_slug_idx on public.service_slide_images using btree (service_slug) TABLESPACE pg_default;

create trigger service_slide_images_set_created_at BEFORE INSERT on service_slide_images for EACH row
execute FUNCTION service_slide_images_set_created_at ();

create trigger service_slide_images_set_updated_at BEFORE
update on service_slide_images for EACH row
execute FUNCTION service_slide_images_set_updated_at ();

create table public.services (
  id uuid not null default extensions.uuid_generate_v4 (),
  slug text not null,
  label text not null,
  headline text not null,
  subline text not null,
  info_title text not null,
  info_paragraphs text[] not null,
  info_bullet_points text[] not null,
  gradient_start text not null,
  gradient_end text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  image_path text null,
  constraint services_pkey primary key (id),
  constraint services_slug_key unique (slug)
) TABLESPACE pg_default;

create trigger services_set_updated_at BEFORE
update on services for EACH row
execute FUNCTION services_set_updated_at ();